import "./style.scss"
import React from "react"
import { nanoid } from "nanoid"
import housesForSale from "./data/housesForSale"
import logo from "./images/logo.png"
import {HouseCard} from "./components/HouseCard.jsx";

export default function App() {
    
/* Challenge

    The JSX of the houseCards being generated by the map method below needs to be put in a separate functional component. Your task is to do so as follows:
    
        1. The current JSX in the return statement of the map method below should be replaced by a 
           single instance of a <HouseCard /> component, which you will have to create. 
           
        2. The HouseCard component should return the same JSX as is currently being returned inside 
           the map method. 
		
		3. The variables in the JSX should become props, which will need to be passed into the 
           <HouseCard /> you will be returning in the map method. 
		   
		4. The HouseCard component should be placed in a separate file in the components folder and 
           imported into this App.jsx file.
        
        5. You should only pass up to a maximum of four props being into <HouseCard />. You 
           *should not* manually pass every piece of houseData as a seperate prop! The site should look and behave exactly the same once you've completed these tasks. The challenge here is just about improving the code "underneath the hood"!
*/
    
	const houseCards = housesForSale.map((houseData, index, array) => {
		return (<HouseCard houseData={houseData} index={index} array={array}/>)
	})

	return (
		<div className="challenge_08">
			<div className="wrapper">
				<header>
					<img className="logo" src={logo} alt="logo"/>
				</header>
				<div className="house-cards-container">
					{houseCards}
				</div>
			</div>
		</div>
	)
}
